---

- name: Add helm awx-operator repo
  kubernetes.core.helm_repository:
    name: "{{ awx_helm_operator_version }}"
    repo_url: "{{ awx_helm_operator_repo }}"

- name: Deploy Awx Operator through helm
  kubernetes.core.helm:
    name: "{{ awx_operator_name }}"
    namespace: "{{ awx_namespace }}"
    create_namespace: true
    chart_ref: awx-operator/awx-operator
    values_files:
      - '{{ awx_operator_dir }}/{{ awx_customvalues }}'

- name: Wait till the Object is created
  kubernetes.core.k8s_info:
    kind: Pod
    wait: yes
    namespace: '{{ awx_namespace }}'
    wait_sleep: 10
    wait_timeout: 600
